---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: flux-system
spec:
  chart:
    spec:
      version: 1.18.0
  values:
    fullnameOverride: open-webui
    ingress:
      enabled: false
    persistence:
      enabled: true
      existingClaim: openwebui-data
    extraEnvVars:
      - name: OLLAMA_BASE_URL
        value: http://ollama.ollama.svc.cluster.local:11434
      - name: UVICORN_WORKERS
        value: "1"
      - name: AIOHTTP_CLIENT_TIMEOUT
        value: "300"
    service:
      type: ClusterIP
      port: 8080
      