---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: db-openwebui
  namespace: flux-system
spec:
  path: ./infrastructure/databases/openwebui/base
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: cloudnative-pg
  sourceRef:
    kind: GitRepository
    name: flux-systemn
