---
apiVersion: v1
kind: Namespace
metadata:
  name: ollama
  labels:
    app.kubernetes.io/part-of: app
    app.kubernetes.io/part-of: ollama
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
  labels:
    app.kubernetes.io/part-of: app
    app.kubernetes.io/part-of: open-webui