apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      version: 1.18.0
  values:
    fullnameOverride: external-dns
    provider: azure
    sources:
      - gateway-httproute
      - gateway-grpcroute
    serviceAccount:
      annotations:
        azure.workload.identity/client-id: "ab49cf48-e2d3-4d79-afdc-54b364ef2502" # Updated with the Client ID of the managed identity
        azure.workload.identity/use: "true"
    podLabels:
      azure.workload.identity/use: "true"
    logLevel: debug
    domainFilters:
      - staging.testhop.xyz
    txtOwnerId: external-dns-staging
    extraVolumes:
      - name: azure-config-file
        secret:
          secretName: external-dns-azure
    extraVolumeMounts:
      - name: azure-config-file
        mountPath: /etc/kubernetes
        readOnly: true
