---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  interval: 15m
  chart:
  spec:
    chart: ollama
    version: "*"                 # pin/adjust as you prefer
    sourceRef:
      kind: HelmRepository
      name: otwld
      namespace: flux-system
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: warn
  targetNamespace: ollama